// Niumba - Sample Data for Development
import { Property, Category, Owner } from '../types';

export const CATEGORIES: Category[] = [
  { id: 'house', name: 'Maison', nameEn: 'House', icon: 'home' },
  { id: 'apartment', name: 'Appartement', nameEn: 'Apartment', icon: 'building' },
  { id: 'flat', name: 'Studio', nameEn: 'Flat', icon: 'door-closed' },
  { id: 'dormitory', name: 'Dortoir', nameEn: 'Dormitory', icon: 'bed' },
  { id: 'townhouse', name: 'Duplex', nameEn: 'Townhouse', icon: 'home-city' },
  { id: 'land', name: 'Terrain', nameEn: 'Land', icon: 'terrain' },
  { id: 'commercial', name: 'Commercial', nameEn: 'Commercial', icon: 'store' },
  { id: 'warehouse', name: 'Entrepôt', nameEn: 'Warehouse', icon: 'warehouse' },
];

export const SAMPLE_OWNERS: Owner[] = [
  {
    id: 'owner-1',
    name: 'Jean-Pierre Mwamba',
    company: 'Mwamba Immobilier SARL',
    phone: '+243 97 123 4567',
    email: 'contact@mwamba-immo.cd',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    isVerified: true,
    propertiesCount: 24,
  },
  {
    id: 'owner-2',
    name: 'Marie Kasongo',
    company: 'Kasongo Properties',
    phone: '+243 81 234 5678',
    email: 'marie@kasongo-properties.cd',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    isVerified: true,
    propertiesCount: 18,
  },
  {
    id: 'owner-3',
    name: 'Patrick Kabongo',
    phone: '+243 99 345 6789',
    email: 'patrick.kabongo@email.cd',
    isVerified: false,
    propertiesCount: 5,
  },
];

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Villa Moderne Golf',
    titleEn: 'Modern Golf Villa',
    type: 'house',
    price: 350000,
    currency: 'USD',
    priceType: 'sale',
    address: 'Avenue du Golf, Quartier Golf',
    city: 'Lubumbashi',
    province: 'Haut-Katanga',
    latitude: -11.6876,
    longitude: 27.4847,
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    garage: 2,
    description: 'Magnifique villa moderne située dans le prestigieux quartier Golf de Lubumbashi. Cette propriété exceptionnelle offre un cadre de vie luxueux avec des finitions haut de gamme.',
    descriptionEn: 'Beautiful modern villa located in the prestigious Golf neighborhood of Lubumbashi. This exceptional property offers a luxurious living environment with high-end finishes.',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800',
    ],
    features: ['Piscine', 'Jardin', 'Sécurité 24h', 'Groupe électrogène', 'Forage'],
    featuresEn: ['Swimming Pool', 'Garden', '24h Security', 'Generator', 'Borehole'],
    owner: SAMPLE_OWNERS[0],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
    isFeatured: true,
    isAvailable: true,
    views: 234,
  },
  {
    id: 'prop-2',
    title: 'Appartement Centre-Ville',
    titleEn: 'Downtown Apartment',
    type: 'apartment',
    price: 1500,
    currency: 'USD',
    priceType: 'rent',
    rentPeriod: 'month',
    address: 'Avenue Kasavubu, Centre-Ville',
    city: 'Lubumbashi',
    province: 'Haut-Katanga',
    latitude: -11.6642,
    longitude: 27.4794,
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    garage: 1,
    description: 'Superbe appartement au cœur de Lubumbashi, idéal pour les professionnels. Proximité des commerces et bureaux.',
    descriptionEn: 'Superb apartment in the heart of Lubumbashi, ideal for professionals. Close to shops and offices.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    features: ['Climatisation', 'Ascenseur', 'Parking', 'Internet fibre'],
    featuresEn: ['Air Conditioning', 'Elevator', 'Parking', 'Fiber Internet'],
    owner: SAMPLE_OWNERS[1],
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-18T16:00:00Z',
    isFeatured: true,
    isAvailable: true,
    views: 189,
  },
  {
    id: 'prop-3',
    title: 'Maison Familiale Kolwezi',
    titleEn: 'Family House Kolwezi',
    type: 'house',
    price: 180000,
    currency: 'USD',
    priceType: 'sale',
    address: 'Quartier Mutoshi',
    city: 'Kolwezi',
    province: 'Lualaba',
    latitude: -10.7167,
    longitude: 25.4667,
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    garage: 1,
    description: 'Belle maison familiale dans un quartier calme de Kolwezi. Parfait pour une famille avec enfants.',
    descriptionEn: 'Beautiful family house in a quiet neighborhood of Kolwezi. Perfect for a family with children.',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    features: ['Jardin', 'Citerne', 'Panneau solaire', 'Clôture sécurisée'],
    featuresEn: ['Garden', 'Water Tank', 'Solar Panel', 'Secured Fence'],
    owner: SAMPLE_OWNERS[2],
    createdAt: '2024-01-05T12:00:00Z',
    updatedAt: '2024-01-12T09:00:00Z',
    isFeatured: false,
    isAvailable: true,
    views: 156,
  },
  {
    id: 'prop-4',
    title: 'Entrepôt Zone Industrielle',
    titleEn: 'Industrial Zone Warehouse',
    type: 'warehouse',
    price: 5000,
    currency: 'USD',
    priceType: 'rent',
    rentPeriod: 'month',
    address: 'Zone Industrielle Kipushi',
    city: 'Kipushi',
    province: 'Haut-Katanga',
    latitude: -11.7667,
    longitude: 27.2333,
    bedrooms: 0,
    bathrooms: 2,
    area: 1200,
    garage: 0,
    description: 'Grand entrepôt dans la zone industrielle, idéal pour stockage ou activité commerciale. Accès facile pour camions.',
    descriptionEn: 'Large warehouse in the industrial zone, ideal for storage or commercial activity. Easy truck access.',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
      'https://images.unsplash.com/photo-1553413077-190dd305871c?w=800',
    ],
    features: ['Grande surface', 'Quai de chargement', 'Sécurité', 'Électricité triphasée'],
    featuresEn: ['Large Surface', 'Loading Dock', 'Security', 'Three-phase Power'],
    owner: SAMPLE_OWNERS[0],
    createdAt: '2024-01-08T14:00:00Z',
    updatedAt: '2024-01-15T11:00:00Z',
    isFeatured: false,
    isAvailable: true,
    views: 87,
  },
  {
    id: 'prop-5',
    title: 'Terrain Commercial Likasi',
    titleEn: 'Commercial Land Likasi',
    type: 'land',
    price: 75000,
    currency: 'USD',
    priceType: 'sale',
    address: 'Avenue Principale, Centre Likasi',
    city: 'Likasi',
    province: 'Haut-Katanga',
    latitude: -10.9833,
    longitude: 26.7333,
    bedrooms: 0,
    bathrooms: 0,
    area: 2000,
    garage: 0,
    description: 'Terrain commercial stratégiquement situé au centre de Likasi. Idéal pour construction de centre commercial ou immeuble de bureaux.',
    descriptionEn: 'Strategically located commercial land in the center of Likasi. Ideal for shopping center or office building construction.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    ],
    features: ['Titre foncier', 'Zone commerciale', 'Accès route principale'],
    featuresEn: ['Land Title', 'Commercial Zone', 'Main Road Access'],
    owner: SAMPLE_OWNERS[1],
    createdAt: '2024-01-03T10:00:00Z',
    updatedAt: '2024-01-10T08:00:00Z',
    isFeatured: true,
    isAvailable: true,
    views: 203,
  },
  {
    id: 'prop-6',
    title: 'Duplex Moderne Lubumbashi',
    titleEn: 'Modern Duplex Lubumbashi',
    type: 'townhouse',
    price: 2800,
    currency: 'USD',
    priceType: 'rent',
    rentPeriod: 'month',
    address: 'Quartier Bel-Air',
    city: 'Lubumbashi',
    province: 'Haut-Katanga',
    latitude: -11.6500,
    longitude: 27.4800,
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    garage: 2,
    description: 'Magnifique duplex dans le quartier résidentiel Bel-Air. Construction récente avec matériaux de qualité.',
    descriptionEn: 'Magnificent duplex in the residential Bel-Air neighborhood. Recent construction with quality materials.',
    images: [
      'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800',
    ],
    features: ['Terrasse', 'Cuisine équipée', 'Dressing', 'Groupe électrogène'],
    featuresEn: ['Terrace', 'Equipped Kitchen', 'Walk-in Closet', 'Generator'],
    owner: SAMPLE_OWNERS[2],
    createdAt: '2024-01-12T09:00:00Z',
    updatedAt: '2024-01-19T15:00:00Z',
    isFeatured: true,
    isAvailable: true,
    views: 312,
  },
];

export const getFeaturedProperties = (): Property[] => {
  return SAMPLE_PROPERTIES.filter(p => p.isFeatured);
};

export const getPropertiesByCity = (city: string): Property[] => {
  return SAMPLE_PROPERTIES.filter(p => p.city === city);
};

export const getPropertiesByType = (type: string): Property[] => {
  return SAMPLE_PROPERTIES.filter(p => p.type === type);
};

export const getPropertyById = (id: string): Property | undefined => {
  return SAMPLE_PROPERTIES.find(p => p.id === id);
};

